# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ASN')),
                ('code', models.IntegerField(verbose_name='Code ASN')),
            ],
        ),
        migrations.CreateModel(
            name='FileZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('asn', models.IntegerField(unique=True)),
                ('geo', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('infection', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=200)),
                ('ic_ip', models.CharField(max_length=100)),
                ('ic_port', models.IntegerField()),
                ('ic_asn', models.IntegerField()),
                ('ic_geo', models.CharField(max_length=50)),
                ('ic_dns', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('proxy', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=50)),
                ('p0f_genre', models.CharField(max_length=50)),
                ('p0f_detail', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=50)),
                ('id1', models.IntegerField()),
                ('naics', models.IntegerField()),
                ('sic', models.IntegerField()),
                ('cc_naics', models.IntegerField()),
                ('cc_sic', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('cc_sector', models.CharField(max_length=100)),
                ('ssl_cipher', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('public_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du dossier')),
                ('url', models.CharField(max_length=200, verbose_name='Chemin du dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Imap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Infections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom su virus')),
            ],
        ),
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.CharField(max_length=100, verbose_name='Adresse ipv4')),
                ('ipv6', models.CharField(max_length=100, verbose_name='Adresse ipv6')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Votre nom', max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('contact', models.CharField(max_length=8, verbose_name='Contact(s)')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('adresse', models.CharField(max_length=30, verbose_name='Adresse')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('photo', models.ImageField(default=0, upload_to='images', verbose_name='Choisir une photo')),
            ],
        ),
    ]
